added echo to print the message

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,8 +25,8 @@ jobs:
       - name: Build with Gradle
         run: gradle clean build -x test
 
-      - name: Get commit ID
-        run: echo "COMMIT_ID=$(echo $COMMIT | cut -c1-7)" >> $GITHUB_ENV
+      - name: Get commit Id
+        run: echo "COMMIT_ID=$(echo $COMMIT | cut -c1-8)" >> $GITHUB_ENV
 
       - name: Log in to DockerHub
         uses: docker/login-action@v3
@@ -36,8 +36,11 @@ jobs:
 
       - name: Build Docker image
         run: |
+          echo "🔧 Building image: ${{ secrets.DOCKERHUB_USERNAME }}/notification_processor:$COMMIT_ID"
           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notification_processor:${COMMIT_ID} .
 
       - name: Push Docker image to DockerHub
         run: |
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification_processor:${COMMIT_ID}
+          echo " 📤 Pushing image: ${{ secrets.DOCKERHUB_USERNAME }}/notification_processor:$COMMIT_ID"
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification_processor:${COMMIT_ID} || { echo '❌ Image Push failed'; exit 1; }
+          echo " ✅ Image pushed "
